frequency: 10.0
broadcast_cartesian_transform: false        # global EKF publishes map->odom TF instead
broadcast_cartesian_transform_as_parent_frame: false
publish_filtered_gps: true
datum: [17.50969045486119, 78.27728104672221, 0.0]
wait_for_datum: false
use_odometry_yaw: true               # use odom yaw to help align GPS->map orientation
yaw_offset: 0.0

world_frame: map
base_link_frame: base_link
odom_frame: odom

gps_topic: /navsat/fix
gps_vel_topic: /navsat/vel
odom_topic: /odometry/filtered      # EKF output odometry topic or raw odom (choose appropriate)
imu_topic: /imu/data  