frequency: 10.0
broadcast_cartesian_transform: true        # publishes map->utm / map->odom TFs
broadcast_cartesian_transform_as_parent_frame: true
publish_filtered_gps: true
datum_lat: 17.509690
datum_lon: 78.277281
datum_alt: 0.0
wait_for_datum: false                # true = wait for initial datum; false uses configured datum
use_odometry_yaw: true               # use odom yaw to help align GPS->map orientation
yaw_offset: 0.0

world_frame: map
base_link_frame: base_link
odom_frame: odom

gps_topic: /navsat/fix
gps_vel_topic: /navsat/vel
odom_topic: /odometry/filtered      # EKF output odometry topic or raw odom (choose appropriate)
imu_topic: /imu/data  